### ISSUE TITLE
Java application

### ISSUE THREAD

**Issue by Prier** [lbr-stack/pyFRI#12]
Hi 

The repository that the link to the Java application points to: https://github.com/cmower/LBR-Java-app does not seem to be available any more, what program should be used for sunrise, if I want to try the driver? 

Btw. the project looks great!

**Comment by mhubii** [comment]
hi @Prier and sorry for the late reply. We are still in the process of pulling the project together nicely.

In the meantime, you could for example use this application 

https://github.com/lbr-stack/fri/tree/ros2-fri-1.15/server_app
