### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by CameronDevine** [lbr-stack/pyfri#15]
As part of the JOSS review (openjournals/joss-reviews#6138) API documentation is required. I am finding some documentation in the Readme, and some in the Wiki, but I don't believe this is sufficient. Looking at the examples, there are a lot of methods that are not documented.

**Comment by mhubii** [comment]
I agree, the `pyFRI` is rather a weak-spot of this submission. We will have to make some improvements here. Thank you for the pointing this out

**Comment by adi3** [comment]
@mhubii see if using [Komment](https://www.komment.ai) helps you get this through.

**Comment by mhubii** [comment]
I'd love to try that

**Comment by mhubii** [comment]
okay wow that was quite easy. Tested on a single file, created a PR

https://github.com/lbr-stack/pyFRI/pull/16

This does seem to support Python right now?

**Comment by mhubii** [comment]
added documentation for examples, and the overall software architecture. Referred to in-depth KUKA documentation for the FRI, as these are just bindings.
